spring:
  cloud:
    config:
      server:
        git:
          uri : https://github.com/chaudharydevender95/cloud-config-server.git

management:
  endpoints:
    web:
      exposure:
        include: "*"